version: '4.35.1'
services:
  postgres:
    container_name: tcc-backend-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tcc-music
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres