services:
  postgres:
    container_name: tcc-backend-pg
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: datapostgres
      POSTGRES_DB: tcc-music
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
